### ISSUE TITLE
0.27.3 breaks most accountsservice tests

### ISSUE THREAD

**Issue by heftig** [martinpitt/python-dbusmock#118]
I've updated from 0.25.0 to 0.27.3. Since then, the accountsservice tests are broken.

E.g.:

```
10/12 accountsservice:accounts-service+libaccountsservice+TestAccountsService / TestAccountsService.test_recreate_user            FAIL            0.32s   exit status 1
>>> GI_TYPELIB_PATH=/build/accountsservice/src/build/src/libaccountsservice G_DEBUG=fatal-criticals G_MESSAGES_DEBUG=all MALLOC_PERTURB_=56 LD_LIBRARY_PATH=/build/accountsservice/src/build/src/libaccountsservice /usr/bin/python3 /build/accountsservice/src/build/../accountsservice/tests/test-libaccountsservice.py TestAccountsService.test_recreate_user
――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
test_recreate_user (__main__.TestAccountsService) ... (process:2193): accountsservice-DEBUG: 16:08:09.032: Finding a graphical session for user 1042
(process:2193): accountsservice-DEBUG: 16:08:09.032: Failed to identify the current session
(process:2193): accountsservice-DEBUG: 16:08:09.032: ActUserManager: seat unloaded, so trying to set loaded property
(process:2193): accountsservice-DEBUG: 16:08:09.032: ActUserManager: Seat wouldn't load, so giving up on it and setting loaded property
(process:2193): accountsservice-DEBUG: 16:08:09.032: ActUserManager: already loaded, so not setting loaded property
(process:2193): accountsservice-DEBUG: 16:08:09.032: ActUserManager: Creating user 'pizza', 'I Love Pizza', 1
(process:2193): accountsservice-DEBUG: 16:08:09.033: ActUserManager: calling 'ListCachedUsers'
(process:2193): accountsservice-DEBUG: 16:08:09.034: ActUserManager: ListCachedUsers finished with empty list, maybe setting loaded property now
(process:2193): accountsservice-DEBUG: 16:08:09.034: ActUserManager: already loaded, so not setting loaded property
ERROR

======================================================================
ERROR: test_recreate_user (__main__.TestAccountsService)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/accountsservice/src/build/../accountsservice/tests/test-libaccountsservice.py", line 111, in test_recreate_user
    self._manager.create_user('pizza', 'I Love Pizza',
gi.repository.GLib.GError: g-io-error-quark: GDBus.Error:org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/dbus/service.py", line 715, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3.10/site-packages/dbusmock/mockobject.py", line 135, in wrapper
    return func(*args, **kwargs)
  File "<string>", line 173, in CreateUser
  File "/usr/lib/python3.10/site-packages/dbusmock/mockobject.py", line 133, in wrapper
    self.MethodCalled(fname, log_args)
  File "/usr/lib/python3.10/site-packages/dbus/decorators.py", line 325, in emit_signal
    message.append(signature=signature, *args)
TypeError: Expected a string or unicode object
 (36)

----------------------------------------------------------------------
Ran 1 test in 0.229s
```

The test calls `CreateUser`, which results in an internal call of `AddUser` with the arguments `2001`, `dbus.String('pizza')`, `dbus.String('Pa$$wo0rd')` and `{'RealName': 'I Love Pizza', 'AccountType': dbus.Int32(1)}`.

The problem seems to be that the logging added in https://github.com/martinpitt/python-dbusmock/commit/f8709a9d14b722bbf112c2e52f201a5dccefaba4 disregards the signature of the called method. It just sends all arguments into `MethodCalled`'s `'av'` parameter, resulting in `dbus-python` guessing the type for each item. In the case of the dict this results in a guess of `a{ss}` based on its first item, which then blows up on the `Int32`.

**Comment by martinpitt** [comment]
Sorry about that! @whot fixed this, that landed in master now. I am reverting a hack in PR #121 that confirms that the fix worked.

One of these days we need to get the accountsservice tests actually working in upstream CI. They were broken on all OSes when they got introduced (as they depended on unreleased stuff), but maybe now they work somewhere. I'll put that on my TODO list.

But first, I [released 0.27.4](https://github.com/martinpitt/python-dbusmock/releases/tag/0.27.4) with the fix.
