### ISSUE TITLE
Build error with 0.28.5

### ISSUE THREAD

**Issue by z3ntu** [martinpitt/python-dbusmock#164]
When building the latest version for Alpine Linux from https://files.pythonhosted.org/packages/source/p/python-dbusmock/python-dbusmock-0.28.5.tar.gz I'm getting the following exception, probably linked to this item in the release notes (without actually looking into it more)

> * Use setuptools_scm to determine version

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/setuptools/config/expand.py", line 80, in __getattr__
    return next(
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/setuptools/config/expand.py", line 190, in read_attr
    return getattr(StaticModule(module_name, spec), attr_name)
  File "/usr/lib/python3.10/site-packages/setuptools/config/expand.py", line 86, in __getattr__
    raise AttributeError(f"{self.name} has no attribute {attr}") from e
AttributeError: dbusmock has no attribute __version__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/builder/aports/community/py3-dbusmock/src/python-dbusmock-0.28.5/setup.py", line 7, in <module>
    setuptools.setup()
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 159, in setup
    dist.parse_config_files()
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 864, in parse_config_files
    setupcfg.parse_configuration(
  File "/usr/lib/python3.10/site-packages/setuptools/config/setupcfg.py", line 174, in parse_configuration
    meta.parse()
  File "/usr/lib/python3.10/site-packages/setuptools/config/setupcfg.py", line 496, in parse
    section_parser_method(section_options)
  File "/usr/lib/python3.10/site-packages/setuptools/config/setupcfg.py", line 470, in parse_section
    self[name] = value
  File "/usr/lib/python3.10/site-packages/setuptools/config/setupcfg.py", line 278, in __setitem__
    value = parser(value)
  File "/usr/lib/python3.10/site-packages/setuptools/config/setupcfg.py", line 602, in _parse_version
    return expand.version(self._parse_attr(value, self.package_dir, self.root_dir))
  File "/usr/lib/python3.10/site-packages/setuptools/config/setupcfg.py", line 412, in _parse_attr
    return expand.read_attr(attr_desc, package_dir, root_dir)
  File "/usr/lib/python3.10/site-packages/setuptools/config/expand.py", line 194, in read_attr
    return getattr(module, attr_name)
AttributeError: module 'dbusmock' has no attribute '__version__'
```

**Comment by martinpitt** [comment]
Right, sorry about that. The release tarball got built on Ubuntu 22.04, which apparently has a buggy python3-setuptools-scm. I marked 0.28.5 as pre-release last night, and will investigate/fix/release a 0.28.6 now.

**Comment by martinpitt** [comment]
In particular:
```
$ cat dbusmock/_version.py
'''auto-generated version from setuptools_scm '''__version__ = "0.28.5"
```
(missing line break)

**Comment by martinpitt** [comment]
Fixed in https://github.com/martinpitt/python-dbusmock/releases/tag/0.28.6

**Comment by lissyx** [comment]
@martinpitt Could it be possible this regressed at least on 0.32.2? https://treeherder.mozilla.org/logviewer?job_id=478870258&repo=try&lineNumber=1070 Seeing the same error here

**Comment by martinpitt** [comment]
@lissyx Commit 7bbb4cd0077cea7e67ad10c9e2c8ebfd1eeab7a3 (which is part of 0.32.2) should have robustified that, there is no line break in the template any more. 

It seems correct in the tarball?
```
❱❱❱ curl -L https://github.com/martinpitt/python-dbusmock/releases/download/0.32.2/dist.python-dbusmock-0.32.2.tar.gz  | tar xzO python-dbusmock-0.32.2/dbusmock/_version.py
__version__ = "0.32.2"
```

What does your build do, start from git, the official release tarball, or perhaps gihub's autogenerated tar/zip (which don't contain the pregenerated version.py)?

**Comment by martinpitt** [comment]
Ah, the log finally loaded -- it says it uses https://pypi.pub.build.mozilla.org/pub/python-dbusmock-0.32.2.tar.gz , but that's the same tarball. No off-hand idea, I'm afraid :cry: Can this be reproduced somehow in a standard distro container or similar?

**Comment by lissyx** [comment]
> Ah, the log finally loaded -- it says it uses https://pypi.pub.build.mozilla.org/pub/python-dbusmock-0.32.2.tar.gz , but that's the same tarball. No off-hand idea, I'm afraid 😢 Can this be reproduced somehow in a standard distro container or similar?

Unfortunately I cannot reproduce locally so I'm guessing it's something we do on our ci 😭. Thanks for checking!

**Comment by lissyx** [comment]
> > Ah, the log finally loaded -- it says it uses https://pypi.pub.build.mozilla.org/pub/python-dbusmock-0.32.2.tar.gz , but that's the same tarball. No off-hand idea, I'm afraid 😢 Can this be reproduced somehow in a standard distro container or similar?
> 
> Unfortunately I cannot reproduce locally so I'm guessing it's something we do on our ci 😭. Thanks for checking!

FTR as a colleague reported on bugzilla we reproduce when we change the index that pip uses ... weird but at least i can track it down
