### ISSUE TITLE
Tests failing if all run at the same time

### ISSUE THREAD

**Issue by ukBaz** [martinpitt/python-dbusmock#24]
I'm having some problems getting my tests to run correctly. I am looking to split my tests into separate files.
If I run the two test files separately then all the tests run correctly. However if I run both test files with one command then the second file to run doesn't run successfully.

The test files are as follows:

```
$ ls -1 tests/
__init__.py
test_adapter.py
test_device.py
```

This is how I would normally run my tests and I get the error:

```
$ python3 -m unittest discover -v
test_adapter_address (tests.test_adapter.TestBluezeroAdapter) ... ok
test_adapter_alias (tests.test_adapter.TestBluezeroAdapter) ... ok
test_adapter_alias_write (tests.test_adapter.TestBluezeroAdapter) ... ok
test_adapter_discoverable (tests.test_adapter.TestBluezeroAdapter) ... ok
test_adapter_discoverabletimeout (tests.test_adapter.TestBluezeroAdapter) ... ok
test_adapter_discovering (tests.test_adapter.TestBluezeroAdapter) ... ok
test_adapter_name (tests.test_adapter.TestBluezeroAdapter) ... ok
test_adapter_pairable (tests.test_adapter.TestBluezeroAdapter) ... ok
test_adapter_pairabletimeout (tests.test_adapter.TestBluezeroAdapter) ... ok
test_adapter_power (tests.test_adapter.TestBluezeroAdapter) ... ok
test_adapter_power_write (tests.test_adapter.TestBluezeroAdapter) ... ok
test_start_discovery (tests.test_adapter.TestBluezeroAdapter) ... skipped 'mock of discovery not implemented'
test_device_name (tests.test_device.TestBluezeroDevice) ... ERROR

======================================================================
ERROR: test_device_name (tests.test_device.TestBluezeroDevice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/python/python-bluezero/tests/test_device.py", line 40, in test_device_name
    found_name = ble_dev.name()
  File "/home/pi/python/python-bluezero/bluezero/device.py", line 36, in name
    constants.DEVICE_INTERFACE, 'Name')
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownObject: Method "Get" with signature "ss" on interface "org.freedesktop.DBus.Properties" doesn't exist


----------------------------------------------------------------------
Ran 13 tests in 10.369s

FAILED (errors=1, skipped=1)
```

I don't see this error if the files are run separately:

```
$ python3 -m unittest -v tests.test_adapter
test_adapter_address (tests.test_adapter.TestBluezeroAdapter) ... ok
test_adapter_alias (tests.test_adapter.TestBluezeroAdapter) ... ok
test_adapter_alias_write (tests.test_adapter.TestBluezeroAdapter) ... ok
test_adapter_discoverable (tests.test_adapter.TestBluezeroAdapter) ... ok
test_adapter_discoverabletimeout (tests.test_adapter.TestBluezeroAdapter) ... ok
test_adapter_discovering (tests.test_adapter.TestBluezeroAdapter) ... ok
test_adapter_name (tests.test_adapter.TestBluezeroAdapter) ... ok
test_adapter_pairable (tests.test_adapter.TestBluezeroAdapter) ... ok
test_adapter_pairabletimeout (tests.test_adapter.TestBluezeroAdapter) ... ok
test_adapter_power (tests.test_adapter.TestBluezeroAdapter) ... ok
test_adapter_power_write (tests.test_adapter.TestBluezeroAdapter) ... ok
test_start_discovery (tests.test_adapter.TestBluezeroAdapter) ... skipped 'mock of discovery not implemented'

----------------------------------------------------------------------
Ran 12 tests in 7.534s

OK (skipped=1)

$ python3 -m unittest -v tests.test_device
test_device_name (tests.test_device.TestBluezeroDevice) ... ok

----------------------------------------------------------------------
Ran 1 test in 3.555s

OK
```

Is there something special I need to do if I want to run my tests in this way?

**Comment by martinpitt** [comment]
This isn't much to go on. Can you please try with the current version? PR #47 fixed a race condition with parallel tests.

**Comment by martinpitt** [comment]
Closing due to lack of response in two years. If you still run into this with the current version, please reopen/yell and describe a reproducer? I'm happy to look into it then. Thanks!
