### ISSUE TITLE
'string signature' under python 2

### ISSUE THREAD

**Issue by elbenfreund** [martinpitt/python-dbusmock#26]
When running ``dbusmock`` under python 2 unicode strings passed to a mocked method cause an error when they contain characters that can not be encoded using ascii.

According to the [dbus docs](https://dbus.freedesktop.org/doc/dbus-python/api/dbus.String-class.html) dbus strings that can be specified in a signature default to unicode, if the ``utf8_strings`` kwarg has not been set to ``True`` in the method decorator.

When passing such a unicode string containing non ascii chars to a mocked method with ``in_sig='s'`` the following error occurs:

```
E       DBusException: org.freedesktop.DBus.Python.UnicodeEncodeError: Traceback (most recent call last):
E         File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb
E           retval = candidate_method(self, *args, **keywords)
E         File "/home/elbenfreund/.virtualenvs/hamster-dbus/local/lib/python2.7/site-packages/dbusmock/mockobject.py", line 330, in <lambda>
E           self, interface, name, in_sig, *args, **kwargs)
E         File "/home/elbenfreund/.virtualenvs/hamster-dbus/local/lib/python2.7/site-packages/dbusmock/mockobject.py", line 551, in mock_method
E           self.log(dbus_method + self.format_args(args))
E         File "/home/elbenfreund/.virtualenvs/hamster-dbus/local/lib/python2.7/site-packages/dbusmock/mockobject.py", line 599, in format_args
E           s += format_arg(a)
E         File "/home/elbenfreund/.virtualenvs/hamster-dbus/local/lib/python2.7/site-packages/dbusmock/mockobject.py", line 578, in format_arg
E           return '"' + str(a) + '"'
E       UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-9: ordinal not in range(128)
```

At a first glance this seems to be due to the use of ``str`` in L578 which means something different between py2 and py3. Maybe using ``six.text_type`` or something similar can avoid a forced type conversion here?

Please let me know if I can provide any further information to help sorting this issue
Eric

**Comment by martinpitt** [comment]
Indeed this is quite simple to reproduce:
```
❱❱❱ python -c "x = u'foo♥'; print(str(x))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode characters in position 3-5: ordinal not in range(128)
```
Argh, I'm so looking forward to dropping Python 2 :-)

I can reproduce this with this test case, which works in Python 3 but fails in Python 2:
```diff
--- a/tests/test_api.py
+++ b/tests/test_api.py
@@ -78,6 +78,13 @@ class TestAPI(dbusmock.DBusTestCase):
         self.dbus_mock.AddMethod('', 'Do', 's', 's', 'ret = args[0]')
         self.assertEqual(self.dbus_test.Do('Hello'), 'Hello')
 
+    def test_unicode_str(self):
+        '''unicode string roundtrip'''
+
+        self.dbus_mock.AddMethod('', 'Do', 's', 's', 'ret = args[0] * 2')
+        self.assertEqual(self.dbus_test.Do(b'a\xe2\x99\xa5b'.decode('UTF-8')),
+                         dbus.String(b'a\xe2\x99\xa5ba\xe2\x99\xa5b'.decode('UTF-8')))
+
     def test_twoarg_ret(self):
         '''two arguments, code for return value'''
```
