### ISSUE TITLE
0.21.0: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [martinpitt/python-dbusmock#64]
```
+ cd python-dbusmock-0.21.0
+ /usr/bin/python3 setup.py test
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing python_dbusmock.egg-info/PKG-INFO
writing dependency_links to python_dbusmock.egg-info/dependency_links.txt
writing top-level names to python_dbusmock.egg-info/top_level.txt
reading manifest file 'python_dbusmock.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'python_dbusmock.egg-info/SOURCES.txt'
running build_ext
/usr/lib64/python3.8/site-packages/dbus/decorators.py:330: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
  args = inspect.getargspec(func)[0]
test_add_object (test_api.TestAPI)
add a new object ... ok
test_add_object_existing (test_api.TestAPI)
try to add an existing object ... ok
test_add_object_with_methods (test_api.TestAPI)
add a new object with methods ... ok
test_array_arg (test_api.TestAPI)
array argument ... ok
test_dbus_get_log (test_api.TestAPI)
query call logs over D-Bus ... ok
test_dbus_get_method_calls (test_api.TestAPI)
query method call logs over D-Bus ... ok
test_dbus_method_called (test_api.TestAPI)
subscribe to MethodCalled signal ... ok
test_dict_arg (test_api.TestAPI)
dictionary argument ... ok
test_introspection_methods (test_api.TestAPI)
dynamically added methods appear in introspection ... ok
test_introspection_properties (test_api.TestAPI)
dynamically added properties appear in introspection ... ok
test_methods_on_other_interfaces (test_api.TestAPI)
methods on other interfaces ... ok
test_methods_same_name (test_api.TestAPI)
methods with same name on different interfaces ... ok
test_methods_type_mismatch (test_api.TestAPI)
calling methods with wrong arguments ... ok
test_noarg_noret (test_api.TestAPI)
no arguments, no return value ... ok
test_objects_map (test_api.TestAPI)
access global objects map ... ok
test_onearg_noret (test_api.TestAPI)
one argument, no return value ... ok
test_onearg_ret (test_api.TestAPI)
one argument, code for return value ... ok
test_properties (test_api.TestAPI)
add and change properties ... ok
test_reset (test_api.TestAPI)
resetting to pristine state ... ok
test_signals (test_api.TestAPI)
emitting signals ... ok
test_signals_type_mismatch (test_api.TestAPI)
emitting signals with wrong arguments ... ok
test_twoarg_ret (test_api.TestAPI)
two arguments, code for return value ... ok
test_unicode_str (test_api.TestAPI)
unicode string roundtrip ... ok
test_mock_terminates_with_bus (test_api.TestCleanup)
Spawned mock processes exit when bus goes down ... ok
test_ctor (test_api.TestSubclass)
Override DBusMockObject constructor ... ok
test_none_props (test_api.TestSubclass)
object with None properties argument ... ok
test_local (test_api.TestTemplates)
Load a local template *.py file ... ok
test_local_nonexisting (test_api.TestTemplates) ... ok
test_object_manager (test_api.TestTemplates)
Template with ObjectManager API ... ok
test_reset (test_api.TestTemplates)
Reset() puts the template back to pristine state ... ok
test_static_method (test_api.TestTemplates)
Static method in a template ... ok
test_no_adapters (test_bluez5.TestBlueZ5) ... ok
test_no_devices (test_bluez5.TestBlueZ5) ... ok
test_one_adapter (test_bluez5.TestBlueZ5) ... ok
test_one_device (test_bluez5.TestBlueZ5) ... SKIP: flaky test
test_pairing_device (test_bluez5.TestBlueZ5) ... SKIP: flaky test
test_everything (test_bluez5.TestBlueZObex) ... SKIP: pbap-client not installed (copy it from bluez/test)
test_help (test_cli.TestCLI) ... ok
test_no_args (test_cli.TestCLI) ... ok
test_object_manager (test_cli.TestCLI) ... ok
test_session_bus (test_cli.TestCLI) ... ok
test_system_bus (test_cli.TestCLI) ... ok
test_template_parameters (test_cli.TestCLI) ... ok
test_template_parameters_malformed_json (test_cli.TestCLI) ... ok
test_template_parameters_not_dict (test_cli.TestCLI) ... ok
test_template_system (test_cli.TestCLI) ... ok
test_codestyle (test_code.StaticCodeTests) ... ok
test_pyflakes (test_code.StaticCodeTests) ... ok
test_pylint (test_code.StaticCodeTests) ... ************* Module dbusmock.templates.networkmanager
dbusmock/templates/networkmanager.py:238:0: C0330: Wrong continued indentation (remove 14 spaces).
                                      'ret = [k for k in objects.keys() if "/Devices" in k]'),
                        |             ^ (bad-continuation)
dbusmock/templates/networkmanager.py:245:0: C0330: Wrong continued indentation.
                                                    "self, args[0], args[1], args[2])"),
                        |                           ^                    | (bad-continuation)
ERROR
test_types (test_code.StaticCodeTests) ... SKIP: mypy not installed
test_default_state (test_gnome_screensaver.TestGnomeScreensaver)
Not locked by default ... ok
test_lock (test_gnome_screensaver.TestGnomeScreensaver)
Lock() ... ok
test_set_active (test_gnome_screensaver.TestGnomeScreensaver)
SetActive() ... ok
test_empty (test_logind.TestLogind) ... ok
test_properties (test_logind.TestLogind) ... ok
test_session (test_logind.TestLogind) ... ok
test_low_memory_warning_signal (test_low_memory_monitor.TestLowMemoryMonitor)
LowMemoryWarning signal ... ok
test_add_connection (test_networkmanager.TestNetworkManager) ... ok
test_add_remove_settings (test_networkmanager.TestNetworkManager) ... ok
test_add_update_settings (test_networkmanager.TestNetworkManager) ... ok
test_connectivity_state (test_networkmanager.TestNetworkManager) ... ok
test_eth_and_wifi (test_networkmanager.TestNetworkManager) ... ok
test_get_conn_by_uuid (test_networkmanager.TestNetworkManager) ... ok
test_global_state (test_networkmanager.TestNetworkManager) ... ok
test_networking (test_networkmanager.TestNetworkManager) ... ok
test_one_eth_connected (test_networkmanager.TestNetworkManager) ... ok
test_one_eth_disconnected (test_networkmanager.TestNetworkManager) ... ok
test_one_wifi_with_accesspoints (test_networkmanager.TestNetworkManager) ... ok
test_remove_connection (test_networkmanager.TestNetworkManager) ... ok
test_settings_secrets (test_networkmanager.TestNetworkManager) ... ok
test_two_eth (test_networkmanager.TestNetworkManager) ... ok
test_two_wifi_with_accesspoints (test_networkmanager.TestNetworkManager) ... ok
test_update_connection (test_networkmanager.TestNetworkManager) ... ok
test_wifi_with_active_connection (test_networkmanager.TestNetworkManager) ... ok
test_wifi_with_connection (test_networkmanager.TestNetworkManager) ... ok
test_wifi_without_access_points (test_networkmanager.TestNetworkManager) ... ok
test_close (test_notification_daemon.TestNotificationDaemon)
CloseNotification() and NotificationClosed() signal ... ok
test_id (test_notification_daemon.TestNotificationDaemon)
ID handling ... ok
test_no_options (test_notification_daemon.TestNotificationDaemon)
notify-send with no options ... ok
test_options (test_notification_daemon.TestNotificationDaemon)
notify-send with some options ... ok
test_get_operators_for_two_modems (test_ofono.TestOfono)
Add second modem, list operators on both ... SKIP: ofono scripts not available, set $OFONO_SCRIPT_DIR
test_hangup_all (test_ofono.TestOfono)
multiple outgoing voice calls ... SKIP: ofono scripts not available, set $OFONO_SCRIPT_DIR
test_list_modems (test_ofono.TestOfono)
Manager.GetModems() ... SKIP: ofono scripts not available, set $OFONO_SCRIPT_DIR
test_list_operators (test_ofono.TestOfono)
list operators ... SKIP: ofono scripts not available, set $OFONO_SCRIPT_DIR
test_outgoing_call (test_ofono.TestOfono)
outgoing voice call ... SKIP: ofono scripts not available, set $OFONO_SCRIPT_DIR
test_second_modem (test_ofono.TestOfono)
Add a second modem ... SKIP: ofono scripts not available, set $OFONO_SCRIPT_DIR
test_allow_unknown (test_polkitd.TestPolkit) ... ok
test_default (test_polkitd.TestPolkit) ... ok
test_set_allowed (test_polkitd.TestPolkit) ... ok
test_changing_local_rtc (test_timedated.TestTimedated) ... ok
test_changing_ntp (test_timedated.TestTimedated) ... ok
test_changing_timezone (test_timedated.TestTimedated) ... ok
test_default_local_rtc (test_timedated.TestTimedated) ... ok
test_default_ntp (test_timedated.TestTimedated) ... ok
test_default_timezone (test_timedated.TestTimedated) ... ok
test_charging_battery (test_upower.TestUPower) ... ok
test_discharging_battery (test_upower.TestUPower) ... ok
test_display_device_default (test_upower.TestUPower) ... ok
test_enumerate (test_upower.TestUPower) ... ok
test_no_devices (test_upower.TestUPower) ... ok
test_one_ac (test_upower.TestUPower) ... ok
test_setup_display_device (test_upower.TestUPower) ... ok
test_block (test_urfkill.TestURfkill) ... ok
test_flightmode (test_urfkill.TestURfkill) ... ok
test_flightmode_restore (test_urfkill.TestURfkill) ... ok
test_mainobject (test_urfkill.TestURfkill) ... ok
test_subobjects (test_urfkill.TestURfkill) ... ok

======================================================================
ERROR: test_pylint (test_code.StaticCodeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/python-dbusmock-0.21.0/tests/test_code.py", line 43, in test_pylint
    subprocess.check_call([pylint, '--score=n', '--disable=missing-function-docstring,R0801',
  File "/usr/lib64/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/pylint', '--score=n', '--disable=missing-function-docstring,R0801', '--disable=too-many-arguments,too-many-instance-attributes', 'dbusmock/templates/']' returned non-zero exit status 16.

----------------------------------------------------------------------
Ran 107 tests in 132.114s

FAILED (errors=1, skipped=10)
Test failed: <unittest.runner.TextTestResult run=107 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=107 errors=1 failures=0>
```

**Comment by martinpitt** [comment]
@kloczek : Thanks for your report! That's easy enough to fix, but I'd like to spot such errors in CI in the future. That currently runs current Fedora rawhide's and latest stable (33) pylint, which is 2.6.0. That's also the latest [version on pypi](https://pypi.org/project/pylint/). It looks like you also  have some RPM based distro, which one is that? What's the pylint version there?
