### ISSUE TITLE
Tests fail with Python 3.10

### ISSUE THREAD

**Issue by hadess** [martinpitt/python-dbusmock#74]
Trying to build (and test) python-dbusmock-0.23 in Fedora rawhide against Python 3.10:
```
======================================================================
FAIL: test_methods_type_mismatch (tests.test_api.TestAPI)
calling methods with wrong arguments
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/python-dbusmock-0.23.0/tests/test_api.py", line 189, in check
    self.dbus_test.Do(*args)
  File "/usr/lib64/python3.10/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
  File "/usr/lib64/python3.10/site-packages/dbus/service.py", line 711, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/builddir/build/BUILD/python-dbusmock-0.23.0/dbusmock/mockobject.py", line 400, in <lambda>
    method = lambda self, *args, **kwargs: DBusMockObject.mock_method(
  File "/builddir/build/BUILD/python-dbusmock-0.23.0/dbusmock/mockobject.py", line 661, in mock_method
    m.append(signature=in_signature, *args)
TypeError: 'dbus.String' object cannot be interpreted as an integer
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/builddir/build/BUILD/python-dbusmock-0.23.0/tests/test_api.py", line 205, in test_methods_type_mismatch
    check('i', ['hello'], 'TypeError: an integer is required')
  File "/builddir/build/BUILD/python-dbusmock-0.23.0/tests/test_api.py", line 193, in check
    self.assertIn(err, str(e))
AssertionError: 'TypeError: an integer is required' not found in 'org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):\n  File "/usr/lib64/python3.10/site-packages/dbus/service.py", line 711, in _message_cb\n    retval = candidate_method(self, *args, **keywords)\n  File "/builddir/build/BUILD/python-dbusmock-0.23.0/dbusmock/mockobject.py", line 400, in <lambda>\n    method = lambda self, *args, **kwargs: DBusMockObject.mock_method(\n  File "/builddir/build/BUILD/python-dbusmock-0.23.0/dbusmock/mockobject.py", line 661, in mock_method\n    m.append(signature=in_signature, *args)\nTypeError: \'dbus.String\' object cannot be interpreted as an integer\n'
======================================================================
FAIL: test_signals_type_mismatch (tests.test_api.TestAPI)
emitting signals with wrong arguments
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/python-dbusmock-0.23.0/tests/test_api.py", line 514, in check
    self.dbus_mock.EmitSignal('', 's', signature, args)
  File "/usr/lib64/python3.10/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
  File "/usr/lib64/python3.10/site-packages/dbus/service.py", line 711, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/builddir/build/BUILD/python-dbusmock-0.23.0/dbusmock/mockobject.py", line 583, in EmitSignal
    m.append(signature=signature, *args)
TypeError: 'dbus.String' object cannot be interpreted as an integer
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/builddir/build/BUILD/python-dbusmock-0.23.0/tests/test_api.py", line 530, in test_signals_type_mismatch
    check('i', ['hello'], 'TypeError: an integer is required')
  File "/builddir/build/BUILD/python-dbusmock-0.23.0/tests/test_api.py", line 518, in check
    self.assertIn(err, str(e))
AssertionError: 'TypeError: an integer is required' not found in 'org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):\n  File "/usr/lib64/python3.10/site-packages/dbus/service.py", line 711, in _message_cb\n    retval = candidate_method(self, *args, **keywords)\n  File "/builddir/build/BUILD/python-dbusmock-0.23.0/dbusmock/mockobject.py", line 583, in EmitSignal\n    m.append(signature=signature, *args)\nTypeError: \'dbus.String\' object cannot be interpreted as an integer\n'
----------------------------------------------------------------------
```

**Comment by martinpitt** [comment]
Indeed, thanks @hadess ! The [CI run from 3 days ago](https://github.com/martinpitt/python-dbusmock/actions/runs/927340742) was still happy, but [yesterday's run](https://github.com/martinpitt/python-dbusmock/actions/runs/934550363) shows the same error.
